version: "3.6"

networks:
    flights-network:
        name: flights-network
        external: true

services:
    flights:
        image: gertum/flights:latest
        container_name: flights
        build:
            context: ./
            dockerfile: .docker/flights/Dockerfile
        volumes:
            - ./:/var/www/html
            - ./shared:/var/shared
        #      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        environment:
            BASEDIR: /var/www/html
            COMPOSER_AUTH: '${COMPOSER_AUTH}'
            HOME: /var/www/html
        #      CURRENT_UID: '${CURRENT_UID}'
        #      SYSTEM_UID: '${SYSTEM_UID}'
        #      SYSTEM_GID: '${SYSTEM_GID}'
        depends_on:
              - flights_db
        # user: ${CURRENT_UID}
        networks:
            - flights-network

    flights_db:
        container_name: flights_db
        image: mariadb:latest
        volumes:
            - ./.docker/db/storage/volumes/mysql:/var/lib/mysql
#            - ./.docker/db/resources/database_character_set.sh:/docker-entrypoint-initdb.d/database_character_set.sh
        environment:
            - MYSQL_ROOT_PASSWORD=flightsp
            - MYSQL_USER=flights
            - MYSQL_PASSWORD=flights
            - MYSQL_DATABASE=flights
            - TERM=dumb
        ports:
            - "23311:3306"
        networks:
            - flights-network

    flights_web:
        image: gertum/flights_web:latest
        container_name: flights_web
        build:
            context: ./
            dockerfile: .docker/web/Dockerfile
        links:
            - flights:php_fpm
        ports:
            - "8080:80"
        environment:
            - BASEDIR=/var/www/html

        volumes:
            - ./.docker/web/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html
            - ./shared:/var/shared

        networks:
            - flights-network

        depends_on:
            - flights
